### PR TITLE
Update to support custom syntaxes via settings

### PR DESCRIPTION
**Pull request by aminland**
People keep wanting to add syntaxes. This way, we don't have to update the primary repo to allow them to do so.

### CODE REVIEW

**Comment by braver** [comment]
Isn’t that what the syntax_map is for?

**Comment by aminland** [comment]
Not necessarily, you may want to have multiple linters. Otherwise the current list of syntaxes on the class wouldn't be so large as it is. 

E.g. in my case I wanted to have some coffeescript files run through eslint with a plugin, but I already had another SublimeLinter to do style checking. So I couldn't have both run just using a syntax map (if the map was specified in reverse, i.e. `{ basetype1: [subtype1, ...], ...}` that would work). 
Given that there are a ton of variants which now transpile to to ecmascript I'd say this is the way to go. Just from the existing tickets, this would also alleviate the requests from #177 and #153

**Comment by kaste** [comment]
Heads up, @aminland . I just have to think through this more.

**Comment by kaste** [comment]
PTAL @ https://github.com/SublimeLinter/SublimeLinter/pull/994

I wanted to add this in core, also it had to use the new SL4 API, so I decided to just do it. Esp. since I didn't know ahead of time, if a manageable small PR would suffice, or a major refactoring, pain in the ass, would have to be done.

**Comment by kaste** [comment]
This has been resolved in core via https://github.com/SublimeLinter/SublimeLinter/pull/1007

But thanks for the PR anyway, without it I would have never thought about it in the first place. ❤️

**Pull request closed without merging**
