### PR TITLE
Use `on_stderr` and `notify_failure()`

### PR DESCRIPTION
**Pull request by kaste**
Also demote config missing error to a warning.

### CODE REVIEW

**Comment by braver** [comment]
I'm trying this out myself with stylelint, which has similar behaviour. Is the approach to `notify_failure()` and keep the report/warning at line 0?

**Comment by kaste** [comment]
This PR uses https://github.com/SublimeLinter/SublimeLinter/pull/1301 (a new callback 'on_stderr' still to be discussed/evaled)

**Comment by braver** [comment]
When I test this with SublimeLinter/SublimeLinter#1301 and a project without eslintrc I get this:

screen shot 2018-04-17 at 09 25 59

And the console:

```
plugins loaded
SublimeLinter: WARNING: 
Oops! Something went wrong! :(

ESLint: 4.19.1.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /Users/koenlageveen/Sites/repo-stats and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: ERROR: 
SublimeLinter: WARNING: 
Oops! Something went wrong! :(

ESLint: 4.19.1.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /Users/koenlageveen/Sites/repo-stats and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: ERROR: 
Package Control: Skipping automatic upgrade, last run at 2018-04-17 09:11:04, next run at 2018-04-17 10:11:04 or after
```


Ie. `SublimeLinter: ERROR:` seems to come after the actual error message, which is preceded by `SublimeLinter: WARNING:`

**Comment by kaste** [comment]
Sorry, pushed new commit to core https://github.com/SublimeLinter/SublimeLinter/pull/1301

**Comment by braver** [comment]
Yes, much better 👍

**Comment by braver** [comment]
4.3 has shipped. 🛥 this too?

**Pull request merged**
