### PR TITLE
Add step to sanitise command output before parsing

### LINKED ISSUE #251: eslint output appears in panel, not gutter
Hello everyone,

I am using the latest build of Sublime Text 3.1.1 on macOS High Sierra, and I am no longer seeing eslint output in the gutter; I only see the JSON output in the same warning panel that used to hold Deprecation and Experimental Warnings. I have copied an anonymized version of an eslint "error" that I found in this panel after deliberately messing up a symbol name, and I will paste it below. 

```
SublimeLinter: #6 eslint CLASS_NAME.js ERROR:
====================================================

eslint output:
PROJECT_PATH/config/webpack/loaders
[{"filePath":"PROJECT_PATH/SOURCE_PATH/CLASS_NAME.js","messages":[{"ruleId":"no-undef","severity":2,"message":"'VARIABLE_NAME' is not defined.","line":34,"column":31,"nodeType":"Identifier","source":"REDACTED","endLine":34,"endColumn":44},{"ruleId":"react/jsx-curly-spacing","severity":2,"message":"There should be no space before '}'","line":34,"column":45,"nodeType":"JSXExpressionContainer","source":"REDACTED","fix":{"range":[946,947],"text":""}}],"errorCount":2,"warningCount":0,"fixableErrorCount":1,"fixableWarningCount":0,"source":"REDACTED"}]
```

Please let me know if there is any more information you need. Thank you for your time.

### PR DESCRIPTION
**Pull request by huntie**
This improves resilience by adding a `_get_output_json` method which will sanitise the ESLint command output before attempting to parse the expected JSON string. Right now, this is a basic operation to select the final line printed, see https://github.com/SublimeLinter/SublimeLinter-eslint/issues/251#issuecomment-394148906.

Fixes #251.

### CODE REVIEW

**Comment by kaste** [comment]
I'm totally :+1: here. Will check tomorrow.

**Comment by huntie** [comment]
@kaste I believe `pass` is equiv. to `return None` in Python, but indeed this stuff needs to be well-tested.

Yeah sounds good, that's a lot more idiomatic - I'll amend that now. Will still use `str.split('\n')` given the below, which will remove the need to catch `IndexError`.

```python
>>> 'foo\nbar\n  '.rstrip().splitlines()[-1]
'bar'
>>> ''.rstrip().splitlines()[-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>> '\n'.rstrip().splitlines()[-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>> ''.rstrip().split('\n')[-1]
''

```

**Comment by kaste** [comment]
The reasoning above is fine, but you didn't test this! 😸 With Sublime ships python3.3 and there is actually no json.JSONDecodeError, so ValueError is correct. Also, `_get_output_json` is a method and as such the first arg is `self`.

**Comment by kaste** [comment]
Let's face it, just inline `_get_output_json` bc it's fits on one line anyway.

**Comment by huntie** [comment]
:sweat_smile: Updated.

**Comment by huntie** [comment]
Working properly for me now. Final question remains if we want to store `output_json` as a separate variable in order to hold the full output to print to the user in the error case. It may make sense to overwrite `output` with the expected JSON line, and remove the "Be aware to not log additional info to stdout" line.

**Pull request merged**
