### PR TITLE
Fix crashing when 'line' is not provided by eslint

### PR DESCRIPTION
**Pull request by MicroDroid**
This PR fixes https://github.com/SublimeLinter/SublimeLinter/issues/1650

### CODE REVIEW

**Comment by MicroDroid** [comment]
By the way, set `ecmaVersion` to something like `2090` to reproduce this error.

**Comment by kaste** [comment]
Thanks for the tip. I'll take a look very soon.

**Comment by MicroDroid** [comment]
PR updated.

**Comment by kaste** [comment]
Thanks, that was easier than I thought it would be! (You forgot to `continue` 😁 without that we would have thrown as before, I just pushed it.) 

💐

**Comment by MicroDroid** [comment]
Awesome, thanks! :D

**Pull request merged**
