### PR TITLE
Add JSON as supported syntax.

### PR DESCRIPTION
**Pull request by richardpringle**
Feature from #164

### CODE REVIEW

**Comment by STRML** [comment]
Please merge, SublimeLinter-JSON uses Python's built-in parser which has some issues (https://github.com/SublimeLinter/SublimeLinter-json/issues/11) -- it misses some things like trailing commas in arrays.

**Comment by braver** [comment]
Actually, it doesn't have that issue anymore?

I think you can also use the syntax map to map json to javascript, so that this linter wil run on it?

**Comment by richardpringle** [comment]
^ @STRML 
I honestly stopped using sublime as my regular editor so I don't really care if this lands, but it should if the fix that @braver suggested doesn't work

**Comment by STRML** [comment]
FWIW the python issue does still persist, at least on my machine. Trailing commas are not caught. This PR would fix the issue.

**Comment by braver** [comment]
If set to JSON syntax, the SublimeLinter-json plugin *will* catch trailing commas as far as I can tell.

**Comment by STRML** [comment]
Try this with SublimeLinter-json:

```json
{
  "foo": "bar",
  "baz": [
    "biff",
  ]
}
```

**Comment by kaste** [comment]
What were you smoking? This 'crashes' the plugin if the eslint plugin is not installed. You can't assume it is. And thus running eslint on JSON unconditionally, will usually flood the console with error messages.

**Comment by braver** [comment]
What? You don’t need anything beyond eslint itself for it to lint json. At least I don’t think you do, works on my machine IIRC. Eh, I doubt I was smoking something but I may have been drinking. Not sure. I dunno. 🤔

**Comment by kaste** [comment]
No, you get a parsing error. And, you have json everywhere, so you likely get the error message that eslint could not find a configuration file. 👎

**Comment by braver** [comment]
Oh damn, sorry

**Comment by STRML** [comment]
Was completely unaware as well, appears https://www.npmjs.com/package/eslint-plugin-json is required to be installed globally for this to work properly.

**Comment by richardpringle** [comment]
Oh man... should probably revert this. I had definitely been using `eslint-plugin-json` for a while before making the change.

`.json` should definitely be optional.

**Comment by STRML** [comment]
Is there a way we can make this an option? It's super useful to have - the built-in JSON linting has some bad bugs - so I wouldn't want to see it reverted entirely.

**Comment by kaste** [comment]
I'm pretty sure we figure out how to make this optional/pluggable in SublimeLinter 4 although I'm currently in the dark.

**Pull request closed without merging**
