### PR TITLE
Implement automatic selector if plugins are used

### LINKED ISSUE #253: Automatically detect eslint-plugin-html, and change default selector settings when found
I'm using SublimeText 3.1.1, SublimeLinter 4.6.0, SublimeLinter-eslint 4.1.3.

We first discussed this in #87. I have a multi-developer repository, where we have command line operation, and different editors in use. We really need Sublime & ESLint to work together, so that we can lint html files correctly in all editors and on the command line.

I've discovered that I can get both to work by implementing a user setting of:

```js
{
  "linters": {
    "eslint": {
      "selector": "source.js, text.html.basic, text.xml",
    }
  }
}
```

Rather than try to get multiple developers to set this up, I'd like a way where SublimeLinter-eslint could detect and set this automatically.

I've looked into Sublime's project settings files, but they seem limited - for example, we don't have one at the moment, so existing developers wouldn't be able to be updated automatically (unlike VSCode's default config options).

### LINKED ISSUE #284: Issue with eslint-plugin-svelte3
I've installed [`eslint-plugin-svelte3`](https://github.com/sveltejs/eslint-plugin-svelte3) and it works correctly on the following example code [from the tutorial](https://svelte.dev/tutorial/onmount) when I run eslint from the command line. However in Sublime Text I get `ParseError - Unexpected token` at the start of line 7 (the first letter of `const` is highlighted).

```javascript
<script>
    import { onMount } from 'svelte';

    let photos = [];

    onMount(async () => {
        const res = await fetch('https://jsonplaceholder.typicode.com/photos?_limit=20');
        photos = await res.json();
    })
</script>
```

Using the Show Scope Name command with the cursor at that point results in `source.js` which I thought meant would trigger JavaScript linting. Am I doing something wrong? Thank you.

### PR DESCRIPTION
**Pull request by kaste**
Fixes #253
Closes #284
Closes https://github.com/SublimeLinter/SublimeLinter/issues/1689

The strategy here is to use a wide `selector` in the beginning and
then narrow it down during actual linting.

SublimeLinter needs a good `selector` as a **fast** check to match
views and installed linters because this first check runs on a shared
worker. 

After the first check, it is always possible to abort loud or silently.
We do here silently because it's not a configuration error coming
from the user but an automatic algorithm bailing out.

With this implementation there comes the drawback that we have to flip
the previous default behavior. The default behavior was for the linter
to run on parts of the buffer marked as `source.js` concurrently. E.g.
it did run on the `<script>` tags when viewing a HTML file.

However, this default often did not produce good results. I.e. in an
HTML file it has no notion of gloabls introduced in one script which
are accessible in another script.

If the user wants this behavior, she now has to opt in by setting the
old selector `'source.js - meta.attribute-with-value'` in the settings
on her own.

Implementation risks:

- We deep import `read_json_file`. It is possible that this import can
  break since deep imports are not protected by any deprecation policy.

- We have two side-effects: `self.notify_unassign()` followed by
  `raise PermanentError()`. It is possible that in the future we need
  to signal the same outcome differently.

TODO:

- [x] Update documentation/README
- [x] Write a update message esp. how to restore the old behavior

### CODE REVIEW

**Comment by kaste** [comment]
cc @scottdotjs Can you ckeck this?  I'm not really an eslint guru, so I actually could only check that it doesn't break eslint *without* any plugins, t.i. it still checks 'js' files LOL, and does not check 'html' files.

**Comment by kaste** [comment]
This generally works. I tested with the html and json plugin. 

A bit inconvenient that we only check for `package.json` presence. We cannot detect if it is already installed. And we sure do not detect if it configured which was the trap I took of course.

**Comment by kaste** [comment]
Let's try this.

**Comment by braver** [comment]
🎉

**Comment by scottdotjs** [comment]
> cc @scottdotjs Can you ckeck this? I'm not really an eslint guru, so I actually could only check that it doesn't break eslint _without_ any plugins, t.i. it still checks 'js' files LOL, and does not check 'html' files.

Hey, sorry for not getting back to you - a death in the family had all my attention for a while.

All seems to be working well in my setup with user setting of `text.html` selector to work with Svelte files. Good job!

**Comment by kaste** [comment]
@scottdotjs 🤗

**Pull request merged**
