### PR TITLE
Update README to add instructions about typescript

### PR DESCRIPTION
**Pull request by ktaragorn**
Also clean up a bit.

### CODE REVIEW

**Comment by kaste** [comment]
Hi! Have you seen #287? We generally want to do this automatically. What would be the best dependency to look for. (We basically have a mapping from package to selector in that PR.)

**Comment by karthikbeam** [comment]
@kaste Nice, I would have expected that. [`@typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) should be the right plugin for this?

**Comment by karthikbeam** [comment]
specifically in package.json, the packages used are `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser`, in `eslintrc` it is declared as `@typescript-eslint`

**Comment by kaste** [comment]
I'll take the update here anyways. It's a good reference even if we need to rewrite the README after we land auto-selectors.

For #287, I go with `'@typescript-eslint/parser': 'source.ts'` for now since the parser is needed for eslint to actually read 'ts' files, and then on top of that you can have probably multiple ts linters. That's how I read their README at least.

**Comment by ktaragorn** [comment]
Sounds good, tnx!

**Pull request merged**
